# Generated by Django 6.0.3 on 2026-04-13 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exploitation', '0002_initial'),
        ('planning', '0002_initial'),
        ('referentiel', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotageTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('VALIDE', 'Validé'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('REPORTE', 'Reporté'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=50)),
                ('travail_en_alignement', models.BooleanField(default=False)),
                ('current_step', models.CharField(default='creation', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demande_retrait', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exploitation.demanderetrait')),
                ('entite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travaux_pilotage', to='user.entitemetier')),
                ('note_arret', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exploitation.notearret')),
                ('reference_reseau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referentiel.referencereseau')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travaux_pilotage', to=settings.AUTH_USER_MODEL)),
                ('type_activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.typeactivite')),
            ],
        ),
    ]
