# Generated by Django 6.0.3 on 2026-05-13 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pilotage', '0001_initial'),
        ('planning', '0001_initial'),
        ('security', '0003_alter_permission_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowhistory',
            name='planning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history', to='planning.planning'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pilotage.workflow'),
        ),
        migrations.AddField(
            model_name='workflowhistory',
            name='from_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_départ', to='pilotage.workflowstep'),
        ),
        migrations.AddField(
            model_name='workflowhistory',
            name='to_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_arrivé', to='pilotage.workflowstep'),
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='from_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transition_sortantes', to='pilotage.workflowstep'),
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='to_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transitions_entrantes', to='pilotage.workflowstep'),
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='pilotage.workflow'),
        ),
        migrations.AddField(
            model_name='workflowhistory',
            name='transition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pilotage.workflowtransition'),
        ),
        migrations.AddField(
            model_name='workflowvalidation',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='security.role'),
        ),
        migrations.AddField(
            model_name='workflowvalidation',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='pilotage.workflowstep'),
        ),
        migrations.AddField(
            model_name='workflowvalidation',
            name='transition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='pilotage.workflowtransition'),
        ),
        migrations.AddField(
            model_name='workflowvalidation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('workflow', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='workflowtransition',
            unique_together={('workflow', 'from_step', 'to_step')},
        ),
    ]
