# Generated by Django 6.0.3 on 2026-04-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField()),
                ('to_state', models.CharField()),
            ],
        ),
    ]
