# Generated by Django 6.0.3 on 2026-04-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotage', '0002_transition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='from_state',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transition',
            name='to_state',
            field=models.CharField(max_length=10),
        ),
    ]
