# Generated by Django 6.0.3 on 2026-06-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotage', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='description',
        ),
        migrations.AlterField(
            model_name='workflow',
            name='code',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
