# Generated by Django 6.0.3 on 2026-04-29 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotage', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowtransition',
            name='to_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transitions_entrantes', to='pilotage.workflowstep'),
        ),
    ]
