# Generated by Django 5.1.13 on 2026-06-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotage', '0003_remove_workflow_description_alter_workflow_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
