version: '3.8'

services:
  db:
    image: mysql:8.4.9
    container_name: mysql_db1
    restart: always
    environment:
      MYSQL_DATABASE: ${DJANGO_DATABASE_NAME}
      MYSQL_USER: ${DJANGO_DATABASE_USER}
      MYSQL_PASSWORD: ${DJANGO_DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DJANGO_DATABASE_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: django_api1
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8002:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  db_data:
  static_volume:
  media_volume: