# Generated by Django 6.0.3 on 2026-05-23 14:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centrale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('capacite_mw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valeur', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TypeReferentiel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferentielItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valeur', models.CharField(max_length=255)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='referentiel.reference')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='referentiel.typereferentiel')),
            ],
        ),
    ]
