# Generated by Django 6.0.3 on 2026-04-08 08:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('nom', models.CharField(max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('actif', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ouvrage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('nom', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('nom', models.CharField(max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('actif', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Troncon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('nom', models.CharField(max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('actif', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceReseau',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('code_reference', models.CharField(max_length=100, unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('actif', models.BooleanField(default=False)),
                ('depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referentiel.depart')),
                ('localisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referentiel.localisation')),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiel.ouvrage')),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referentiel.poste')),
                ('troncon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referentiel.troncon')),
            ],
        ),
    ]
