# Generated by Django 6.0.3 on 2026-05-28 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiel', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='entite_metier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='references', to='user.entitemetier'),
        ),
        migrations.AddField(
            model_name='referentielitem',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='referentiel.reference'),
        ),
        migrations.AddField(
            model_name='referentielitem',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='referentiel.typereferentiel'),
        ),
    ]
