# Generated by Django 6.0.3 on 2026-04-30 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0002_centrale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencereseau',
            name='localisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='referentiel.localisation'),
        ),
    ]
