# Generated by Django 6.0.1 on 2026-01-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0002_depart_date_creation_localisation_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='troncon',
            name='actif',
            field=models.BooleanField(default=False),
        ),
    ]
