# Generated by Django 6.0.1 on 2026-01-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0003_troncon_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='depart',
            name='actif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poste',
            name='actif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referencereseau',
            name='actif',
            field=models.BooleanField(default=False),
        ),
    ]
