# Generated by Django 6.0.3 on 2026-06-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0003_region_reference_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='nom',
        ),
    ]
