# Generated by Django 6.0.1 on 2026-02-06 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0004_depart_actif_poste_actif_referencereseau_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencereseau',
            name='localisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referentiel.localisation'),
        ),
    ]
