# Generated by Django 6.0.3 on 2026-06-24 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0004_remove_region_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrale',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centrales', to='referentiel.region'),
        ),
    ]
