# Generated by Django 5.1.13 on 2026-08-11 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0005_centrale_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referentielitem',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='referentiel.reference'),
        ),
    ]
