# Generated by Django 5.1.13 on 2026-08-11 18:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0007_centrale_date_creation_reference_date_creation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Troncon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valeur', models.CharField(max_length=255, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='referentielitem',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='referentiel.reference'),
        ),
    ]
