# Generated by Django 6.0.3 on 2026-05-13 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pilotage', '0001_initial'),
        ('referentiel', '0003_alter_referencereseau_localisation'),
        ('user', '0004_utilisateur_region_alter_entitemetier_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeActivite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('libelle', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plannings_crees', to=settings.AUTH_USER_MODEL)),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pilotage.workflowstep')),
                ('entite_metier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plannings', to='user.entitemetier')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plannings_modifies', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pilotage.workflow')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Travail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('segment', models.CharField(choices=[('DISTRIBUTION', 'Distribution'), ('TRANSPORT', 'Transport'), ('PRODUCTION', 'Production')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255, unique=True)),
                ('type_reseau', models.CharField(blank=True, choices=[('HTB', 'HTB (Haute Tension)'), ('HTA', 'HTA (Moyenne Tension)'), ('BT', 'BT (Basse Tension)')], max_length=10, null=True)),
                ('consistance_travaux', models.TextField(blank=True)),
                ('troncons_consignes', models.TextField(blank=True)),
                ('localites_impactees', models.CharField(blank=True, max_length=255)),
                ('moyens_mis_en_oeuvre', models.TextField(blank=True)),
                ('heure_debut_planifie', models.DateTimeField(blank=True, null=True)),
                ('duree', models.PositiveIntegerField(blank=True, null=True)),
                ('unite_duree', models.CharField(choices=[('HEURES', 'Heures'), ('JOURS', 'Jours')], default='HEURES', max_length=10)),
                ('heure_fin_planifie', models.DateTimeField(blank=True, null=True)),
                ('date_programmee', models.DateField(blank=True, null=True)),
                ('nombre_jours_avant_travaux', models.PositiveIntegerField(blank=True, null=True)),
                ('disponibilite_mecanique_mw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prevision_puissance_sollicitee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prevision_puissance_interrompue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prevision_enf_mwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qte_fuel_sollicitee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observations', models.TextField(blank=True)),
                ('statut_travaux', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('VALIDE', 'Validé'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('REPORTE', 'Reporté')], default='BROUILLON', max_length=20)),
                ('statut_probleme', models.BooleanField(default=False)),
                ('probleme_rencontre', models.TextField(blank=True)),
                ('travail_en_alignement', models.BooleanField(default=False)),
                ('date_report_travaux', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('centrale_thermique_sollicitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referentiel.centrale')),
                ('charge_consignation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travaux_crees', to=settings.AUTH_USER_MODEL)),
                ('depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referentiel.depart')),
                ('entite_metier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='travaux', to='user.entitemetier')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='travaux_modifies', to=settings.AUTH_USER_MODEL)),
                ('ouvrage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referentiel.ouvrage')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travaux', to='planning.planning')),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referentiel.poste')),
                ('troncon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referentiel.troncon')),
                ('type_travaux', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planning.typeactivite')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
