# Generated by Django 6.0.1 on 2026-01-22 16:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiel', '0001_initial'),
        ('user', '0002_entitemetier_date_creation_role_date_creation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlanningTravaux',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('titre', models.CharField(max_length=255)),
                ('jour_debut_planifie', models.DateField()),
                ('jour_debut_effectif', models.DateField(blank=True, null=True)),
                ('duree_planifiee', models.PositiveIntegerField(help_text='Durée en jours')),
                ('jour_fin_planifie', models.DateField()),
                ('observation', models.TextField(blank=True)),
                ('statut_travaux', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('VALIDE', 'Validé'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('REPORTE', 'Reporté')], max_length=20)),
                ('statut_probleme', models.BooleanField(default=False)),
                ('probleme_rencontre', models.TextField(blank=True)),
                ('travail_en_alignement', models.BooleanField(default=False)),
                ('date_report_travaux', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travaux_crees', to='user.utilisateur')),
                ('modifie_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travaux_modifies', to='user.utilisateur')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiel.referencereseau')),
                ('type_activite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planning.typeactivite')),
            ],
        ),
    ]
