# Generated by Django 6.0.3 on 2026-05-28 15:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PropositionAlignement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_proposition', models.CharField(choices=[('ALIGNEMENT_TRANSPORT', 'Alignement sur transport'), ('ALIGNEMENT_TRAVAUX', 'Alignement entre travaux')], max_length=30)),
                ('type_travaux_reference', models.CharField(blank=True, max_length=100)),
                ('type_travaux_a_modifier', models.CharField(blank=True, max_length=100)),
                ('priorite_travail', models.CharField(blank=True, max_length=5)),
                ('ancien_debut', models.DateTimeField()),
                ('ancienne_fin', models.DateTimeField(blank=True, null=True)),
                ('nouveau_debut', models.DateTimeField()),
                ('nouvelle_fin', models.DateTimeField(blank=True, null=True)),
                ('raison', models.TextField(blank=True)),
                ('note_compatibilite_types', models.TextField(blank=True)),
                ('conflit_charge_consignation', models.BooleanField(default=False)),
                ('detail_conflit', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée'), ('BLOQUEE', 'Bloquée - Conflit charge consignation')], default='EN_ATTENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Travail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('segment', models.CharField(choices=[('DISTRIBUTION', 'Distribution'), ('TRANSPORT', 'Transport'), ('PRODUCTION', 'Production')], max_length=20)),
                ('priorite', models.CharField(blank=True, choices=[('P1', 'P1 - Urgent'), ('P2', 'P2 - Non urgent 1 à 7 jours'), ('P3', 'P3 -  Non urgent 7 jours')], default='P3', max_length=5, null=True)),
                ('type_reseau', models.CharField(blank=True, choices=[('HTB', 'HTB (Haute Tension)'), ('HTA', 'HTA (Moyenne Tension)'), ('BT', 'BT (Basse Tension)')], max_length=10, null=True)),
                ('consistance_travaux', models.TextField(blank=True)),
                ('troncons_consignes', models.TextField(blank=True)),
                ('localites_impactees', models.CharField(blank=True, max_length=255)),
                ('moyens_mis_en_oeuvre', models.TextField(blank=True)),
                ('heure_debut_planifie', models.DateTimeField(blank=True, null=True)),
                ('duree', models.PositiveIntegerField(blank=True, null=True)),
                ('unite_duree', models.CharField(choices=[('HEURES', 'Heures'), ('JOURS', 'Jours')], default='HEURES', max_length=10)),
                ('heure_fin_planifie', models.DateTimeField(blank=True, null=True)),
                ('date_programmee', models.DateField(blank=True, null=True)),
                ('nombre_jours_avant_travaux', models.PositiveIntegerField(blank=True, null=True)),
                ('disponibilite_mecanique_mw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prevision_puissance_sollicitee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prevision_puissance_interrompue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prevision_enf_mwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qte_fuel_sollicitee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observations', models.TextField(blank=True)),
                ('statut_travaux', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('VALIDE', 'Validé'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('REPORTE', 'Reporté')], default='BROUILLON', max_length=20)),
                ('statut_probleme', models.BooleanField(default=False)),
                ('probleme_rencontre', models.TextField(blank=True)),
                ('travail_en_alignement', models.BooleanField(default=False)),
                ('date_report_travaux', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='TypeActivite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('libelle', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
    ]
