# Generated by Django 6.0.3 on 2026-05-28 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pilotage', '0002_initial'),
        ('planning', '0001_initial'),
        ('referentiel', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='cree_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plannings_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planning',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pilotage.workflowstep'),
        ),
        migrations.AddField(
            model_name='planning',
            name='entite_metier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plannings', to='user.entitemetier'),
        ),
        migrations.AddField(
            model_name='planning',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plannings_modifies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planning',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pilotage.workflow'),
        ),
        migrations.AddField(
            model_name='propositionalignement',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propositions_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propositionalignement',
            name='planning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='planning.planning'),
        ),
        migrations.AddField(
            model_name='travail',
            name='centrale_thermique_sollicitee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referentiel.centrale'),
        ),
        migrations.AddField(
            model_name='travail',
            name='charge_consignation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travail',
            name='cree_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travaux_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travail',
            name='entite_metier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='travaux', to='user.entitemetier'),
        ),
        migrations.AddField(
            model_name='travail',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='travaux_modifies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travail',
            name='planning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travaux', to='planning.planning'),
        ),
        migrations.AddField(
            model_name='travail',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travaux', to='referentiel.reference'),
        ),
        migrations.AddField(
            model_name='travail',
            name='unite_demanderesse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travaux', to='user.unitedemanderesse'),
        ),
        migrations.AddField(
            model_name='propositionalignement',
            name='travail_a_modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions_modification', to='planning.travail'),
        ),
        migrations.AddField(
            model_name='propositionalignement',
            name='travail_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propositions_reference', to='planning.travail'),
        ),
        migrations.AddField(
            model_name='typeactivite',
            name='entite_metier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='types_activite', to='user.entitemetier'),
        ),
        migrations.AddField(
            model_name='travail',
            name='type_travaux',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planning.typeactivite'),
        ),
    ]
