# Generated by Django 6.0.3 on 2026-04-08 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0001_initial'),
        ('referentiel', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningtravaux',
            name='cree_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travaux_crees', to='user.utilisateur'),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='modifie_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travaux_modifies', to='user.utilisateur'),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiel.referencereseau'),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='type_activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planning.typeactivite'),
        ),
    ]
