# Generated by Django 6.0.3 on 2026-04-23 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pilotage', '0002_initial'),
        ('planning', '0001_initial'),
        ('referentiel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planningtravaux',
            name='cree_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travaux_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='current_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_plannings', to='pilotage.workflowstep'),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='modifie_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travaux_modifies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiel.referencereseau'),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plannings', to='pilotage.workflow'),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='type_activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planning.typeactivite'),
        ),
    ]
