# Generated by Django 6.0.3 on 2026-06-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travail',
            name='niveau_coupure',
            field=models.CharField(blank=True, choices=[('POSTES', 'coupure au niveau du Postes(affecte tous les départs)'), ('DEPARTS', 'Départs (affecte seulement les départs concernés)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='travail',
            name='type_alignement',
            field=models.CharField(blank=True, choices=[('TRANSPORT', 'transport'), ('DISTRIBUTION_POSTE_SOURCE', 'Distribution - Poste source'), ('DISTRIBUTION_LIGNE', 'Distribution - Ligne'), ('PRODUCTION', 'Production')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='travail',
            name='nombre_jours_avant_travaux',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travail',
            name='unite_duree',
            field=models.CharField(choices=[('HEURES', 'Heures'), ('JOURS', 'Jours'), ('SEMAINES', 'Semaines')], default='HEURES', max_length=10),
        ),
    ]
