# Generated by Django 6.0.3 on 2026-04-29 10:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotage', '0003_alter_workflowtransition_to_step'),
        ('planning', '0002_initial'),
        ('referentiel', '0002_centrale'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeConsignation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('matricule', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='planningtravaux',
            options={},
        ),
        migrations.RenameField(
            model_name='planningtravaux',
            old_name='observation',
            new_name='consistance_travaux',
        ),
        migrations.RenameField(
            model_name='planningtravaux',
            old_name='jour_debut_effectif',
            new_name='date_programmee',
        ),
        migrations.RemoveField(
            model_name='planningtravaux',
            name='duree_planifiee',
        ),
        migrations.RemoveField(
            model_name='planningtravaux',
            name='jour_debut_planifie',
        ),
        migrations.RemoveField(
            model_name='planningtravaux',
            name='jour_fin_planifie',
        ),
        migrations.RemoveField(
            model_name='planningtravaux',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='planningtravaux',
            name='type_activite',
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='centrale_thermique_sollicitee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referentiel.centrale'),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referentiel.depart'),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='disponibilite_mecanique_mw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='duree',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='heure_debut_planifie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='heure_fin_planifie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='localites_impactees',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='moyens_mis_en_oeuvre',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='nombre_jours_avant_travaux',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='observations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='ouvrage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referentiel.ouvrage'),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referentiel.poste'),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='prevision_enf_mwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='prevision_puissance_interrompue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='prevision_puissance_sollicitee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='qte_fuel_sollicitee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='segment',
            field=models.CharField(choices=[('DISTRIBUTION', 'Distribution'), ('TRANSPORT', 'Transport'), ('PRODUCTION', 'Production')], default='DISTRIBUTION', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='troncon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referentiel.troncon'),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='troncons_consignes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='type_reseau',
            field=models.CharField(blank=True, choices=[('HTB', 'HTB (Haute Tension)'), ('HTA', 'HTA (Moyenne Tension)'), ('BT', 'BT (Basse Tension)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='type_travaux',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planning.typeactivite'),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='unite_demanderesse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.entitemetier'),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='unite_duree',
            field=models.CharField(choices=[('HEURES', 'Heures'), ('JOURS', 'Jours')], default='HEURES', max_length=10),
        ),
        migrations.AlterField(
            model_name='planningtravaux',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pilotage.workflowstep'),
        ),
        migrations.AlterField(
            model_name='planningtravaux',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='planningtravaux',
            name='reference',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='planningtravaux',
            name='statut_travaux',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('VALIDE', 'Validé'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('REPORTE', 'Reporté')], default='BROUILLON', max_length=20),
        ),
        migrations.AlterField(
            model_name='planningtravaux',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pilotage.workflow'),
        ),
        migrations.AddField(
            model_name='planningtravaux',
            name='charge_consignation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.chargeconsignation'),
        ),
    ]
