# Generated by Django 6.0.3 on 2026-07-07 22:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropositionAlignement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ancien_debut', models.DateTimeField()),
                ('ancienne_fin', models.DateTimeField()),
                ('nouveau_debut', models.DateTimeField()),
                ('nouvelle_fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée'), ('BLOQUEE', 'Bloquée')], default='EN_ATTENTE', max_length=20)),
                ('conflit_charge_consignation', models.BooleanField(default=False)),
                ('detail_conflit', models.TextField(blank=True)),
                ('note_compatibilite_types', models.CharField(blank=True, max_length=255)),
                ('ressource_commune', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propositions_creees', to=settings.AUTH_USER_MODEL)),
                ('decide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propositions_decidees', to=settings.AUTH_USER_MODEL)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions_alignement', to='planning.planning')),
                ('travail_a_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions_recues', to='planning.travail')),
                ('travail_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions_emises', to='planning.travail')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
