# Generated by Django 6.0.3 on 2026-04-30 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploitation', '0004_alter_notearret_charge_consignation'),
        ('planning', '0003_chargeconsignation_alter_planningtravaux_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningtravaux',
            name='charge_consignation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ChargeConsignation',
        ),
    ]
