# Generated by Django 6.0.3 on 2026-06-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_travail_niveau_coupure_travail_type_alignement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travail',
            name='niveau_coupure',
            field=models.CharField(blank=True, choices=[('POSTES', 'coupure au niveau du Postes(affecte tous les départs)'), ('RAME', 'coupure au niveau de la Rame (affecte tous les départs de la rame)'), ('DEPARTS', 'Départs (affecte seulement les départs concernés)')], max_length=20, null=True),
        ),
    ]
