# Generated by Codex on 2026-08-08

from django.db import migrations, models


def transmit_existing_created_plannings(apps, schema_editor):
    Planning = apps.get_model('planning', 'Planning')
    WorkflowStep = apps.get_model('pilotage', 'WorkflowStep')

    for planning in Planning.objects.filter(current_step__code='CREER').select_related('workflow'):
        if not planning.workflow_id:
            continue
        target_step = WorkflowStep.objects.filter(
            workflow_id=planning.workflow_id,
            code='EN_ATTENTE',
        ).first()
        if target_step:
            planning.current_step_id = target_step.id
            planning.transmis_au_responsable = True
            planning.save(update_fields=['current_step', 'transmis_au_responsable'])


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_alter_travail_niveau_coupure'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='date_transmission',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='transmis_au_responsable',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(transmit_existing_created_plannings, migrations.RunPython.noop),
    ]
