# Generated by Django 6.0.3 on 2026-04-30 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_alter_planningtravaux_charge_consignation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningtravaux',
            name='cree_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plannings_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planningtravaux',
            name='modifie_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plannings_modifies', to=settings.AUTH_USER_MODEL),
        ),
    ]
