# Generated by Django 6.0.3 on 2026-08-08 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_propositionalignement'),
        ('planning', '0004_alter_travail_niveau_coupure'),
    ]

    operations = [
    ]
