# Generated by Django 6.0.3 on 2026-08-08 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_merge_20260808_1706'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propositionalignement',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='propositionalignement',
            old_name='date_creation',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='propositionalignement',
            name='date_decision',
        ),
        migrations.RemoveField(
            model_name='propositionalignement',
            name='decide_par',
        ),
        migrations.RemoveField(
            model_name='propositionalignement',
            name='ressource_commune',
        ),
        migrations.AddField(
            model_name='propositionalignement',
            name='priorite_travail',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='propositionalignement',
            name='raison',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='propositionalignement',
            name='type_proposition',
            field=models.CharField(choices=[('ALIGNEMENT_TRANSPORT', 'Alignement sur transport'), ('ALIGNEMENT_TRAVAUX', 'Alignement entre travaux')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propositionalignement',
            name='type_travaux_a_modifier',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='propositionalignement',
            name='type_travaux_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='propositionalignement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='propositionalignement',
            name='ancienne_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propositionalignement',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propositions_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propositionalignement',
            name='note_compatibilite_types',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='propositionalignement',
            name='nouvelle_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propositionalignement',
            name='planning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='planning.planning'),
        ),
        migrations.AlterField(
            model_name='propositionalignement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée'), ('BLOQUEE', 'Bloquée - Conflit charge consignation')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='propositionalignement',
            name='travail_a_modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions_modification', to='planning.travail'),
        ),
        migrations.AlterField(
            model_name='propositionalignement',
            name='travail_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propositions_reference', to='planning.travail'),
        ),
    ]
