# Generated by Django 6.0.3 on 2026-08-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_merge_20260823'),
    ]

    operations = [
        migrations.AddField(
            model_name='travail',
            name='duree_reelle_heures',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='travail',
            name='end_realise_mwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='travail',
            name='heure_debut_reel',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travail',
            name='heure_fin_reel',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travail',
            name='segment',
            field=models.CharField(choices=[('DISTRIBUTION', 'Distribution'), ('TRANSPORT', 'Transport'), ('PRODUCTION', 'Production'), ('DACOR', 'Dacor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='travail',
            name='statut_travaux',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('VALIDE', 'Validé'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('REPORTE', 'Reporté'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=20),
        ),
    ]
