# Generated by Django 6.0.3 on 2026-05-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('PLAN', 'Planning'), ('DDR', 'DDR'), ('NAPT', 'NAPT')], max_length=20),
        ),
    ]
