# Generated by Django 6.0.3 on 2026-04-08 08:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntiteMetier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('PROD', 'Production'), ('TRANS', 'Transport'), ('DIST', 'Distribution')], max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('actif', models.BooleanField(default=False)),
                ('ldap_req', models.BooleanField(blank=True, default=False, null=True)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('first_connection', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('entite_metier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='user.entitemetier')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='security.role')),
            ],
        ),
    ]
