# Generated by Django 6.0.3 on 2026-06-22 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0004_remove_region_nom'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitemetier',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entite_metier', to='referentiel.region'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='referentiel.region'),
        ),
    ]
