# Generated by Django 6.0.3 on 2026-05-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitemetier',
            name='type',
            field=models.CharField(choices=[('PROD', 'Planning'), ('TRANS', 'Transport'), ('DIST', 'Distribution')], max_length=10),
        ),
    ]
