# Generated by Django 6.0.3 on 2026-04-14 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_initial'),
        ('user', '0002_utilisateur_date_joined_utilisateur_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entitemetier',
            old_name='date_creation',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='entitemetier',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='date_creation',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='nom',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='ldap_req',
            new_name='is_ldap',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='prenom',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='entite_metier',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='last_connection_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='modify_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='modify_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='first_connection',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='security.userrole'),
        ),
    ]
