# Generated by Django 6.0.1 on 2026-02-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_entitemetier_date_creation_role_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='code_role',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
