# Generated by Django 6.0.3 on 2026-05-10 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_entitemetier_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='entite_metier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entite_metier', to='user.entitemetier'),
        ),
    ]
