# Generated by Django 6.0.3 on 2026-05-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_utilisateur_entite_metier'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entitemetier',
            name='type',
            field=models.CharField(choices=[('PROD', 'Production'), ('TRANS', 'Transport'), ('DIST', 'Distribution')], max_length=10),
        ),
    ]
