# Generated by Django 6.0.1 on 2026-02-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_role_code_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='first_connection',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='ldap_req',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
