# Generated by Django 6.0.3 on 2026-04-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_date_creation_entitemetier_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='last_connection_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
