# Generated by Django 6.0.3 on 2026-04-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_utilisateur_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
